name: Bug report
description: Create a report to help us improve.
title: "[Issue]: "
labels: "Type: Bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug form!
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug as accurately as possible.
      placeholder: |
       1: Go to '...'
       2: Click on '....'
       3: Scroll down to '....'
       4: See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: desktop
    attributes:
      label: Desktop, please complete the following information.
      placeholder: |
       OS: [e.g. iOS]
       Browser: [e.g. chrome, safari]
       Version: [e.g. 22]
    validations:
      required: false
  - type: textarea
    id: smartphone
    attributes:
      label: Smartphone, please complete the following information.
      placeholder: |
       Device: [e.g. iPhone6]
       OS: [e.g. iOS8.1]
       Browser: [e.g. stock browser, safari]
       Version: [e.g. 22]
    validations:
      required: false      
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
