name: Question
description: If you have a question, please fill out this form.
title: "[Question]: "
labels: "Type: Question"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out the question form!
  - type: textarea
    id: question
    attributes:
      label: Describe your question
      description: A clear and concise description of your question.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your question.
    validations:
      required: false
