#
# Module manifest for module 'PSGet_BISF'
#
# Generated by: Benjamin Ruoff / Matthias Schlimm / Mike Bijl / Florian Frank
#
# Generated on: 24.07.2019
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'BISF.psm1'

# Version number of this module.
ModuleVersion = '6.1.2'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '632e959f-fff8-40ee-96f4-d8fb3f122a9f'

# Author of this module
Author = 'Benjamin Ruoff / Matthias Schlimm / Mike Bijl / Florian Frank'

# Company or vendor of this module
CompanyName = 'Login Consultants'

# Copyright statement for this module
Copyright = '(c) 2016 Benjamin Ruoff / Matthias Schlimm / Mike Bijl / Florian Frank. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This module contains functions and global variables needed for the Login Consultants Base Image Script Framework (BISF)
  Author: Benjamin Ruoff
  Date: 11.03.2014

  History
  Last Change: 11.03.2014 BR: Script created -function Get-Adaptername  
  Last Change: 13.03.2014 MS: add function Show-MessageBox (thx to BR)
  Last Change: 18.03.2014 BR: new functions added (Write-Log, Set-Logfile, Invoke-FolderScripts)
  Last Change: 21.03.2014 MS: last code change before release to web
  Last Change: 01.04.2014 MS: added central functions and global environment variables from 10_XX_LIB_Config.ps1
  Last Change: 15.05.2014 MS: add function get-version, to display this in the console window
  Last Change: 06.08.2014 MS: Add function ChangeNetworkProviderOrder
  Last Change: 11.08.2014 MS: change function set-Logfile to a single LogFile, like $LOG = "$regdata_log1\$LogFileName"
  Last Change: 11.08.2014 MS: add $Global:hkcu_software= "HKCU:\SOFTWARE"
  Last Change: 12.08.2014 MS: add function CheckPVSSoftware to check BNDevice.exe
  Last Change: 12.08.2014 MS: move Set-Logfile to 10_XX_LIB_Config.ps1 / remove CheckLogDir
  Last Change: 14.08.2014 MS: add Type for Info, Warning, Error for function Write-Log, exit script if Type = Error
  Last Change: 15.08.2014 MS: function Get-Adaptername: add check AdapterIndex IF (!($AdapterIndex -eq $null))...
  Last Change: 15.08.2014 MS: Change Title to "Base Image Script Framework (BIS-F)"
  Last Change: 15.08.2014 MS: add function get-OSinfo
  Last Change: 15.08.2014 MS: add function CheckXDSoftware
  Last Change: 19.08.2014 MS: line 43: reduce PVSDiskDrive to 2 strings if variable exists -> $env:PVSWriteCacheDisk.Substring(0,2)
  Last Change: 19.08.2014 MS: move function progressbar from 98_XX_PrepPVS_BUILD_vDisk.ps1 to this script 
  Last Change: 19.08.2014 MS: add function get-LogContent
  Last Change: 31.10.2014 MB: Renamed functions: Progressbar -> Show-progressbar / CheckXDSoftware -> Test-XDSoftware / CheckPVSSoftware -> Test-PVSSoftware / ChangeNetworkProviderOrder -> Set-NetworkProviderOrder / CheckPSVersion -> Get-PSVersion 
  Last Change: 31.10.2014 MB: Renamed variables: hklm_sw -> hklm_software / hklm_sys -> hklm_system / hkcu_sw -> hkcu_software / CTX_PVS_SCRIPTS -> CTX_BISF_SCRIPTS / $LogFolderName = "BISLogs" -> $LogFolderName = "BISFLogs" / hklm_software_LIC_CTX_PVS_SCRIPTS -> hklm_software_LIC_CTX_BISF_SCRIPTS
  Last Change: 06.02.2015 MS: add function Get-PendingReboot to BISF.psd1
  Last Change: 24.04.2015 MS: change powershell minimum version to 3.0, because with version 2.0 the psd1 would not loaded corretly
  Last Change: 21.08.2015 MS: Change Request 77 - remove all XX,XA,XD from al files and Scripts
'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '@()'

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'http://www.loginconsultants.com/de/ueber-uns/news/tech-update/item/base-image-script-framework-bis-f'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
DefaultCommandPrefix = 'BISF'

}

